on:
  push:
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: 'Flatpak'
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: .flatpak-builder
          key: mpv-flatpak-${{ github.sha }}
          restore-keys: mpv-flatpak-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: mpv.flatpak
          manifest-path: io.mpv.Mpv.yml
          cache: false

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v3
        if: always()
        with:
          path: .flatpak-builder
          key: ${{ steps.cache.outputs.cache-primary-key }}
